export const REQUEST_INSERT_RECORD = "REQUEST_INSERT_RECORD"
export const SUCCESS_INSERT_RECORD = "SUCCESS_INSERT_RECORD"
export const FAILURE_INSERT_RECORD = "FAILURE_INSERT_RECORD"

export const REQUEST_GET_RECORD = "REQUEST_GET_RECORD"
export const SUCCESS_GET_RECORD = "SUCCESS_GET_RECORD"
export const FAILURE_GET_RECORD = "FAILUGETERT_RECORD"